#!/bin/bash

#SFDC deployment script #
##########################

#          Description
# -------------------------------------------------------------------#
#SUBJECT=SFDC Deployment script
#https://wiki.cadence.com/confluence/pages/viewpage.action?pageId=218020658
#
#jbakshi@cadence.com, debarshi@cadence.com, jsaini@cadence.com
#VERSION=0.1.0
# -------------------------------------------------------------------#

#export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-11.b12.el7.x86_64
#export PATH=$JAVA_HOME/bin:$PATH
#which java
#java -version


main()
{
	exec 1> >(logger  -s -t   SFDC_DEPLOY:["${SFDC_ORG}"] ) 2>&1 #Logger 	
	echo "..............START "${SFDC_ORG}" DEPLOYMENT..............."
	echo "======================================================"
	OPTS $@
	VAR
	Email_Alert     #email alert
	check_Lock_arg  #check Lock & dependency
	Trap            #handle Ctrl-C
	Check_Trigger   #whether build is enable/disable            #handle Ctrl-C
	GIT_rev         #collect GIT rev
	create_Cset		#generate changeset
	StaticResource  #generate staticresource .resource
	CusMetadata		#copy customMetadata along with object
	ForceDeploy     #insert/delete as per buid/forcedeploy.txt
	CheckAPIver
	create_Wflow    #generate workflow
	CodeAnalyser
	CustomLabels_Prep
	aura_Prep
	lwc_Prep
	CountDeployable #do nothing if no deployable
#############################
	ReplaceSapceToTabInClass
	Chg_NonProd_Objs # Email masking and object change for Non prod
	ChangeSetDeploy #Deploy ChangeSet
#	CusSet_Deploy   #Deploy Customsetting
#############################
	Unlock
	echo "..............END  "${SFDC_ORG}" DEPLOYMENT..............."
	echo "======================================================"
}

USAGE() {
cat << EOF  
Usage: 
$0 -h | -o <org-name>
$0 -o <org-name> -F -f <from_GIT> -t <to_GIT>

Options:
-h | --help		Display help, this screen

-o | --org		Set SFDC org name ..sbx/dev/hfx/tst/sandbox

-F | --GIT_force	Optional, force GIT range

-f | --GIT_from		Set from_GIT , when -F is declared

-t | --GIT_to		Set to_GIT or L (Latest), when -F is declared

-R | --rleax		Check last successful GIT when -F enforced


EOF
}

#define var
###########
VAR()
{
LOCK=/tmp/$SFDC_ORG.DEPLOY.LOCK
ARG=$#
bin=build/script
property=build/property
buildProperty=${property}/build_${SFDC_ORG}.properties
serverProperty=${property}/${SFDC_ORG}.conf
SFCliBuildList=${property}/${SFDC_ORG}_SFCli.list
deployLogFile=deployUtil/deployTracker/${SFDC_ORG}/DeployLog.log
staticResourceFoldersFile=changeSetDeploy/staticResourceFolders.txt
SFCliBuildList=${property}/${SFDC_ORG}_SFCli.list
SFCliMetaXMLList=${property}/${SFDC_ORG}_SFCliMetaXML.list
SFCliMetaMetaHasFolder=${property}/${SFDC_ORG}_SFCliMetaMetaHasFolder.list
TRIGGER=build/${SFDC_ORG}_trigger
LastSuccessbuild=build/success_githash${SFDC_ORG}
LastSuccessbuildFull=build/success_githash${SFDC_ORG}Full
CUSTOM_SETTING=changeSetDeploy/customSettings/src/env/$SFDC_ORG/customSetting
LOG=/tmp/$SFDC_ORG.Deploy.log
CHANGESETLOG=/tmp/$SFDC_ORG.Changeset.log
CUSETLOG=/tmp/$SFDC_ORG.CusSetting.log
WFLOWLOG=/tmp/$SFDC_ORG.Wflow.log
GIT_LOG=/tmp/$SFDC_ORG.SFDC_GIT.log
GITLOGFORMAT=${bin}/Format_gitLog
HTMLLog=/tmp/${SFDC_ORG}.Deploy.log.html
CUS_HTMLLog=/tmp/${SFDC_ORG}.CusSet.Deploy.log.html
DEPLOYEDFILE=/tmp/${SFDC_ORG}.Deploy.file
CodeAnalyserFILE=CodeAnalyser/CodeAnalysisReport.html
DATE=$(date +"%d%h%Y_%Hh%Mm%Ss")
SetAPI=$(grep ^APIver ${serverProperty}| cut -d "=" -f2)
}




FAIL_EXIT()
{
	echo "deploy failed... exiting.."
	Unlock
}

OPTS() 
{
GIT_FORCE=0
SFDC_ORG=
FROM_GIT=
TO_GIT=
RELAX=
# translate long options to short
for longarg
do
    delim=""
    case "$longarg" in
       --help) longargs="${longargs}-h ";;
       --org) longargs="${longargs}-o ";;
       --GIT_form) longargs="${longargs}-f ";;
       --GIT_to)longargs="${longargs}-t";;
       --GIT_force)longargs="${longargs}-F";;
       --relax)longargs="${longargs}-R";;
       # pass through anything else
       *) [[ "${longarg:0:1}" == "-" ]] || delim="\""
           longargs="${longargs}${delim}${longarg}${delim} ";;
    esac
done
# reset the translated longargs
eval set -- $longargs

#process with long/short option
while getopts ":o:f:t:FRh" opt
do
  case $opt in
    o)SFDC_ORG="$OPTARG" ;;
    f)FROM_GIT="$OPTARG" ;;
    t)TO_GIT="$OPTARG" ;;
    F)GIT_FORCE=1 ;;
    R)RELAX=TRUE ;;
    h)USAGE;exit 1 ;;
   \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
   :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done



if [ $OPTIND -eq 1 ]
then
echo "No options were passed, use option -h|--help for help";exit 1
fi

if ([[ ! -z ${SFDC_ORG} ]] && [[ "$SFDC_ORG" != "praug224" ]] && [[ "$SFDC_ORG" != "tst" ]] && [[ "$SFDC_ORG" != "debarshi" ]] && [[ "$SFDC_ORG" != "sbx" ]] && [[ "$SFDC_ORG" != "sandbox" ]] && [[ "$SFDC_ORG" != "devsandbox" ]])
then
    USAGE
    exit 1
elif ([[ ! -z ${SFDC_ORG} ]] && [[ $GIT_FORCE -ne 1 ]] && [[ -z "$FROM_GIT" ]] && [[  -z "$TO_GIT" ]])
then
echo
elif ([[ $GIT_FORCE -eq 1 ]] || ! [[ "$FROM_GIT" =~ [^[:digit:]] ]] || [[ ! -z "$TO_GIT" ]]) \
&& ([[ ! -z ${SFDC_ORG} ]] && [[ $GIT_FORCE -eq 1 ]] && ! [[ "$FROM_GIT" =~ [^[:digit:]] ]] && [[ ! -z "$TO_GIT" ]] || [[ ! -z "$RELAX" ]])
then
echo
else 
echo "check option -h|--help for force GIT usage"
exit 1
fi
}

check_Lock_arg()
{
	if [ -f $LOCK ]
	then 
		echo "Another deployment process is present...exit" | tee $LOG
		echo ${MAIL_LIST}
		mail -s "${SFDC_ORG} Lock exists, another deployment may in progress" ${MAIL_LIST} < /dev/null
		exit 1
	elif [ ! -d src ]
	then
		echo "src not available"
		exit 1
	elif [ ! -s $LastSuccessbuild ]
	then
		echo "Last sucessfully deployed git rev not found..$LastSuccessbuild not found or empty"
		exit 1
	else
		touch $LOCK
	fi
}

Check_Trigger()
{
	if [ ! -s ${TRIGGER} ]
	then
	echo "file ${TRIGGER} is missing or not set"
	Unlock
	elif [ `cat ${TRIGGER}` -eq 0 ]
	then
	mail -s  "${SFDC_ORG} BuidTrigger is blocked by parent build / manually" $MAIL_LIST  < /dev/null
	echo "${SFDC_ORG} BuidTrigger is blocked by parent build / manually"
	Unlock
	fi      
}

Email_Alert()
{
	dos2unix ${buildProperty}
	CC=$(grep email_cc ${serverProperty} | cut -d "=" -f2)
	TO=$(grep email_to ${serverProperty} | cut -d "=" -f2)
	FROM=$(grep email_from ${serverProperty} | cut -d "=" -f2)
	MAIL_LIST="-r $FROM -c $CC  $TO"
	mutt_MAIL_LIST="$TO -c $CC"
	MAIL=$(grep send_email ${serverProperty} | cut -d "=" -f2)
	case ${MAIL} in
	0) MAIL_DEBUG=$(grep email_debug ${serverProperty} | cut -d "=" -f2)
	   MAIL_LIST=${MAIL_DEBUG}
           mutt_MAIL_LIST=${MAIL_DEBUG}		
	;;
	*) 
	;;
	esac
}


COLLECT_GITLATEST()
{
  	 gitlatest=${TO_GIT}
         if [ ${gitlatest} == 'L' ]
         then
         #update
         git pull
         #collect the branch version only
         gitlatest=$(git log -n1 --format=format:"%H" .)
         fi
}


#last & latest GIT rev
GIT_rev()
{

	PARENTBUILD=$(grep retryFailedBuild ${serverProperty}| cut -d "=" -f2)
	PARENTARGET=$(grep parentTarget ${serverProperty}| cut -d "=" -f2)
	PARENTPATH=$(grep ${PARENTARGET}_Path ${serverProperty}| cut -d "=" -f2)

if [ $GIT_FORCE -eq 1 ]
then
	gitlast=${FROM_GIT}
        COLLECT_GITLATEST

	#Last full deployed revision
        if [ -f ${LastSuccessbuildFull} ]
        then
                gitlastFull=`cat $LastSuccessbuildFull`
        elif [ ! -f ${LastSuccessbuildFull} ]
	then
                echo "set GIT rev of last successful full deployment"
                Unlock
	fi
	
	#Ralx option to check last successful GIT rev	
	if [ ! -z ${RELAX} ] || [ ${RELAX} == "TRUE" ]
	then
	echo "Last successful revision lookup"
	        if [ $gitlatest -eq $gitlastFull ]
                then
                echo "NO FULL Deployment--same GIT rev($gitlatest-$gitlastFull)" | tee $LOG
                echo -e "\n\t FULL Deployment is not possible for same GIT revision. Will be attempted at next schedule" | \
                mail -s "---$SFDC_ORG---NO FULL Deployment--same GIT rev($gitlatest-$gitlastFull) [`TZ=IST date +%d.%b.%Y` IST]" ${MAIL_LIST} 
                Unlock
		fi
	fi
else
	#Latest GIT revision
	#update GIT
	git pull
	#and collect branch version only
	gitlatest=$(git log -n1 --format=format:"%H" src)
	
	#Last deployed revision
	if [ -f $LastSuccessbuild ]
	then
		gitlast=`cat $LastSuccessbuild`
		else
		echo "set GIT rev of last successful deployment"
		Unlock
	fi

fi	
	if [ $gitlatest == $gitlast ]
		then
		echo "NO SF_CLI Deployment--same GIT commit($gitlast-$gitlatest)" | tee $LOG
		echo -e "\n\t Deployment is not possible for same GIT revision. Will be attempted at next schedule" | \
		mail -s "---$SFDC_ORG---NO Deployment--same GIT commit($gitlast-$gitlatest) [`TZ=IST date +%d.%b.%Y` IST]" ${MAIL_LIST} 
		Unlock
	fi
}




create_Cset()
{
    # Start logging with directory check
    if [ -n "${deployLogFile}" ]; then
        log_dir="$(dirname "${deployLogFile}")"
        mkdir -p "${log_dir}"
        echo "Build Started" >> "${deployLogFile}"
    fi
    # Start tee logging
    exec > >(tee -a "${deployLogFile}") 2>&1

    startTime="$(date +"%m/%d/%Y %I:%M:%S %p")"
    echo "Build Start Time - ${startTime}"
    echo "Deploying to ${SFDC_ORG} Environment."
    echo -e "\nPreparing Changeset:"
    echo "Input - From Hash: ${gitlast}"
    echo "Input - To Hash:   ${gitlatest}"

    gitDiffOutput="$(git diff --name-only -r --diff-filter='AMR' "${gitlast}" "${gitlatest}" .)"
    echo -e "\nChanged Files:"
    echo "${gitDiffOutput}"

    echo "Creating Changeset Folder"
    rm -rf changeSetDeploy
    mkdir -p changeSetDeploy/force-app/main/default
    touch "${staticResourceFoldersFile}"

    # Read lists
    if [ -f "${SFCliBuildList}" ]; then
        mapfile -t valid_metadata_types < "${SFCliBuildList}"
    else
        echo "WARNING: Build list file ${SFCliBuildList} not found."
        valid_metadata_types=()
    fi

    if [ -f "${SFCliMetaXMLList}" ]; then
        mapfile -t meta_xml_types < "${SFCliMetaXMLList}"
    else
        echo "WARNING: MetaXML list file ${SFCliMetaXMLList} not found."
        meta_xml_types=()
    fi

    if [ -f "${SFCliMetaMetaHasFolder}" ]; then
        mapfile -t folder_meta_types < "${SFCliMetaMetaHasFolder}"
    else
        folder_meta_types=()
    fi

    in_array() {
        # $1 = needle, remaining = haystack
        local needle="$1"; shift
        local x
        for x in "$@"; do
            [ "${x}" = "${needle}" ] && return 0
        done
        return 1
    }

    copy_file_and_pair() {
        # Ensures both the base and its -meta.xml (if one exists) are copied.
        # $1 = absolute source file path (under src/)
        # $2 = target directory (already created)
        local src_file="$1"
        local target_dir="$2"
        local base=""
        local meta=""

        if [[ "${src_file}" == *"-meta.xml" ]]; then
            meta="${src_file}"
            base="${src_file%-meta.xml}"
        else
            base="${src_file}"
            meta="${src_file}-meta.xml"
        fi

        if [ -f "${base}" ]; then
            cp "${base}" "${target_dir}/"
        fi
        if [ -f "${meta}" ]; then
            cp "${meta}" "${target_dir}/"
        fi
    }

    copy_folder_meta_file() {
        # $1 = metadata_type (reports, email, dashboards, etc.)
        # $2 = folder name
        local mtype="$1"
        local folder="$2"
        local folder_dir="src/${mtype}"
        [ -d "${folder_dir}" ] || return 0

        # Look for any *Folder-meta.xml that starts with the folder name.
        # Typical patterns:
        #   reports/test_folder.reportFolder-meta.xml
        #   email/Unified_Registration_Email_Templates.emailFolder-meta.xml
        #   dashboards/Sales.dashboardFolder-meta.xml
        # Use globbing; if multiple, copy the first (normally there's one).
        local candidate
        shopt -s nullglob
        for candidate in "${folder_dir}/${folder}."*Folder-meta.xml; do
            # Copy to root of that metadata type in the changeset
            mkdir -p "changeSetDeploy/force-app/main/default/${mtype}"
            cp "${candidate}" "changeSetDeploy/force-app/main/default/${mtype}/"
        done
        shopt -u nullglob
    }

    handle_folder_metadata() {
        # $1 = the changed file path (e.g. src/reports/test_folder/Team_Paper.report-meta.xml)
        local file="$1"
        local rel="${file#src/}"             # reports/test_folder/Team_Paper.report-meta.xml
        local mtype="${rel%%/*}"             # reports
        local remainder="${rel#${mtype}/}"   # test_folder/Team_Paper.report-meta.xml

        # Extract folder name = first path component
        local folderName="${remainder%%/*}"  # test_folder
        local fileInsideFolder="${remainder#${folderName}/}" # Team_Paper.report-meta.xml (or deeper)

        # Create target folder structure
        local target_folder_dir="changeSetDeploy/force-app/main/default/${mtype}/${folderName}"
        mkdir -p "${target_folder_dir}"

        # If the changed path itself is the folder meta file at root (e.g. src/reports/test_folder.reportFolder-meta.xml)
        # then just copy it directly under reports (already handled by copy_folder_meta_file call, but include anyway if diff flagged).
        if [[ "${fileInsideFolder}" == "${remainder}" ]] && [[ "${fileInsideFolder}" == *"Folder-meta.xml" ]]; then
            mkdir -p "changeSetDeploy/force-app/main/default/${mtype}"
            cp "${file}" "changeSetDeploy/force-app/main/default/${mtype}/"
            return 0
        fi

        # Copy the component file and its pair
        copy_file_and_pair "${file}" "${target_folder_dir}"

        # Copy folder meta file (if exists)
        copy_folder_meta_file "${mtype}" "${folderName}"
    }

    while IFS= read -r file; do
        [ -z "${file}" ] && continue
        echo "Processing: ${file}"

        # Objects full path preservation
        if [[ "${file}" == src/objects/* ]]; then
            relative_path="${file#src/}"
            target_path="changeSetDeploy/force-app/main/default/${relative_path%/*}"
            mkdir -p "${target_path}"
            cp "${file}" "${target_path}/"
            continue
        fi

        # Email direct files (legacy handling) - but folder-based logic may override if email is in folder types
        if [[ "${file}" == src/email/* ]] && [[ ! -d changeSetDeploy/force-app/main/default/email ]]; then
            : # We allow later logic to process
        fi

        # LWC bundle
        if [[ "${file}" == src/lwc/* ]]; then
            subfolder="$(echo "${file}" | cut -d'/' -f3)"
            target_dir="changeSetDeploy/force-app/main/default/lwc/${subfolder}"
            mkdir -p "${target_dir}"
            cp "${file}" "${target_dir}/"
            meta_file="${file}-meta.xml"
            if [ -f "${meta_file}" ]; then
                cp "${meta_file}" "${target_dir}/"
            fi
            continue
        fi

        # Aura bundle
        if [[ "${file}" == src/aura/* ]]; then
            subfolder="$(echo "${file}" | cut -d'/' -f3)"
            target_dir="changeSetDeploy/force-app/main/default/aura/${subfolder}"
            mkdir -p "${target_dir}"
            cp "${file}" "${target_dir}/"
            meta_file="${file}-meta.xml"
            if [ -f "${meta_file}" ]; then
                cp "${meta_file}" "${target_dir}/"
            fi
            continue
        fi

        # Determine metadata_type & env-specific
        env_specific=false
        if [[ "${file}" == src/env/${SFDC_ORG}/* ]]; then
            metadata_type="$(cut -d'/' -f4 <<< "${file}")"
            env_specific=true
        else
            metadata_type="$(cut -d'/' -f2 <<< "${file}")"
        fi

        # Folder-based types handling (reports/email/dashboards/etc.)
        if in_array "${metadata_type}" "${folder_meta_types[@]}"; then
            # If path is like src/<type>/<folderName>.*Folder-meta.xml (folder meta file at root),
            # treat it slightly differently; our handle function manages both cases.
            handle_folder_metadata "${file}"
            continue
        fi

        # Standard metadata inclusion test
        if in_array "${metadata_type}" "${valid_metadata_types[@]}"; then
            target_dir="changeSetDeploy/force-app/main/default/${metadata_type}"
            mkdir -p "${target_dir}"
            cp "${file}" "${target_dir}/"

            # Pair -meta.xml if required
            if in_array "${metadata_type}" "${meta_xml_types[@]}"; then
                meta_file="${file}-meta.xml"
                if [ -f "${meta_file}" ]; then
                    cp "${meta_file}" "${target_dir}/"
                fi
            fi
        else
            echo "Skipping (not in allowed metadata types): ${file}"
        fi

        # Env-specific remaps
        if [ "${env_specific}" = true ]; then
            case "${metadata_type}" in
                customLabel)
                    mkdir -p "changeSetDeploy/force-app/main/default/labels"
                    cp "${file}" "changeSetDeploy/force-app/main/default/labels/"
                    ;;
                remoteSiteSettings|customMetadata)
                    mkdir -p "changeSetDeploy/force-app/main/default/${metadata_type}"
                    cp "${file}" "changeSetDeploy/force-app/main/default/${metadata_type}/"
                    ;;
            esac
        fi

    done <<< "${gitDiffOutput}"

    echo "Change set preparation completed."

    # Queue user masking
    if [ -d changeSetDeploy/force-app/main/default/queues ]; then
        echo "Masking users in queue"
        # Make regex minimally greedy before </user>
        sed -i "s/@cadence\.com[^<]*<\/user>/@cadence.com.${SFDC_ORG}<\/user>/g" changeSetDeploy/force-app/main/default/queues/*
    else
        echo "No queue"
    fi
}


#Static resource
StaticResource()
{

# Check if static resource folder exists in the changeset
if [ -d "changeSetDeploy/force-app/main/default/staticresources" ]; then
    echo "Static resource folder detected; running detection script..."
    bash ${bin}/detect_staticresource_mod_git_cli.sh ${gitlast}  ${gitlatest} ${SFDC_ORG}
else
    echo "No static resource folder found; skipping static resource detection."
fi

}
ForceDeploy()
{

source ${bin}/forceDeploy_cli.sh ${SFDC_ORG}
}

create_Wflow()
{
    if [ -d changeSetDeploy/force-app/main/default/workflows ]; then
        echo "workflows detected"
        echo "build workflows"
        # Run the new workflow builder script and capture its output.
        antReturnCode=$(bash ${bin}/build-modify-workflows.sh ${SFDC_ORG} 2>&1 | tee ${WFLOWLOG})
        case "$antReturnCode" in
            *trycatch*)
                grep "trycatch" ${WFLOWLOG} | \
                mail -s "---$SFDC_ORG---Workflow Deployment Failed [`TZ=IST date +%d.%b.%Y` IST - git $gitlast-$gitlatest ]" $MAIL_LIST
                echo "Workflow Deployment Failed"
                echo "grep trycatch ${WFLOWLOG}"
                FAIL_EXIT
                ;;
            *)
                cp output/* changeSetDeploy/force-app/main/default/workflows/
                ;;
        esac
    fi
}


CodeAnalyser()
{

rm /tmp/CodeAnalysisReport.txt

	if [ -d changeSetDeploy/force-app/main/default/classes  -o  -d changeSetDeploy/force-app/main/default/triggers ]
	then
		
		bash build/script/currpmd.sh
		bash build/script/createpmdhtml.sh $SFDC_ORG

	else
	
	echo "'classes/' or 'triggers/' not exist. Codebase will not appear." >> /tmp/CodeAnalysisReport.txt
fi
	
}

CustomLabels_Prep()
	
{
ChangeSet_EnvLabel=changeSetDeploy/force-app/main/default/labels
ChangeSet_SrcLabel=changeSetDeploy/force-app/main/default/commonLabel
EnvLabel=src/env/${SFDC_ORG}/customLabel
SrcLabel=src/commonLabel
ChangeSet_Src=changeSetDeploy/force-app/main/default
LastCommonCL=`cat build/LastCommonCL.txt`
LatestCommonCL=`git log -n1 --format=format:"%H" src/commonLabel/CustomLabels.labels-meta.xml`

if [ -d changeSetDeploy/force-app/main/default/labels -o $LastCommonCL != $LatestCommonCL ]
	then
		mkdir changeSetDeploy/force-app/main/default/labels 
		cp -r ${SrcLabel} ${ChangeSet_Src}
		sed -n '/<labels>/,/<\/labels>/p' ${ChangeSet_SrcLabel}/CustomLabels.labels-meta.xml  > ${ChangeSet_Src}/CustomLabels_common_after.labels

		sed -i 's/^[ \t]*//' ${ChangeSet_Src}/CustomLabels_common_after.labels

		sed -i '/<labels>/{n;:l N;/<\/labels>/b; s/\n//; bl}' ${ChangeSet_Src}/CustomLabels_common_after.labels

		sed  -i '/<\/labels>/d ; /<labels>/d' ${ChangeSet_Src}/CustomLabels_common_after.labels
		
		
		sed -n '/<labels>/,/<\/labels>/p' ${ChangeSet_EnvLabel}/CustomLabels.labels-meta.xml  > ${ChangeSet_Src}/CustomLabels_after.labels

		sed -i 's/^[ \t]*//' ${ChangeSet_Src}/CustomLabels_after.labels

		sed -i '/<labels>/{n;:l N;/<\/labels>/b; s/\n//; bl}' ${ChangeSet_Src}/CustomLabels_after.labels

		sed  -i '/<\/labels>/d ; /<labels>/d' ${ChangeSet_Src}/CustomLabels_after.labels
		
		cat ${ChangeSet_Src}/CustomLabels_common_after.labels | while read line
		do
		fullname=`echo ${line} | grep -o -P '(?<=<fullName>).*(?=<\/fullName>)'`

		value=`grep ${fullname} ${ChangeSet_Src}/CustomLabels_after.labels`

		if [ -z "$value" ]
		then
			echo "Value is NULL"
		else
			sed -i "/\b\(${fullname}\)\b/d" ${ChangeSet_Src}/CustomLabels_common_after.labels
		fi

		done
		
		cat ${ChangeSet_Src}/CustomLabels_common_after.labels >> ${ChangeSet_Src}/CustomLabels_after.labels
		touch ${ChangeSet_Src}/CustomLabels_final.labels
		XML=${ChangeSet_Src}/CustomLabels_final.labels

		echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > ${XML}
		echo "<CustomLabels xmlns=\"http://soap.sforce.com/2006/04/metadata\">" >> ${XML}

		#for labels in `cat ${ChangeSet_Src}/CustomLabels_after.labels| awk '{print $1}'`
		cat ${ChangeSet_Src}/CustomLabels_after.labels | while read line
		do

		echo "          <labels>${line}</labels>" >> ${XML}
		done

		echo "</CustomLabels>" >> ${XML}



		rm ${ChangeSet_Src}/CustomLabels_after.labels
		rm ${ChangeSet_Src}/CustomLabels_common_after.labels

		rm ${ChangeSet_EnvLabel}/CustomLabels.labels-meta.xml

		mv ${ChangeSet_Src}/CustomLabels_final.labels ${ChangeSet_EnvLabel}/CustomLabels.labels-meta.xml

		rm -rf ${ChangeSet_SrcLabel}
		
else
	echo "No customLabel found"
fi



#git log -n1 --format=format:"%H" src/commonLabel/CustomLabels.labels-meta.xml > build/LastCommonCL.txt

}


aura_Prep()

{

if [ -d changeSetDeploy/force-app/main/default/aura ]


then
	cd changeSetDeploy/force-app/main/default/aura
	printf '%s\n' */ | while read line
	do	
		echo "$line"
		cp -r ../../../../../src/aura/$line .
		pwd
	done
	cd ../../../../../
else	
		echo "No aura in changeset"
fi
	
}

lwc_Prep()


{

if [ -d changeSetDeploy/force-app/main/default/lwc ]


then
        cd changeSetDeploy/force-app/main/default/lwc
        printf '%s\n' */ | while read line
        do
                echo "$line"
                cp -r ../../../../../src/lwc/$line .
                pwd
        done
        cd ../../../../../
else
                echo "No lwc in changeset"
fi

}


ReplaceSapceToTabInClass()
{

        if [ -d changeSetDeploy/force-app/main/default/classes ]
        then
           echo "==================================="
           echo "Replacing Spaces to tab in classes"
           echo "==================================="
           ###
           cd changeSetDeploy/force-app/main/default/classes
           for file in `ls -1 *.cls*`
           do
              cat $file | sed 's/ *$//' | sed -n ':label1; s/^\(\t*\)    /\1\t/;/^\t*    / b label1; p;' > "${file}"_mod
              echo "====================================="
              ls -l $file "${file}"_mod
              rm $file
              mv "${file}"_mod $file
           done
          cd ../../../../../
     fi
pwd
}

CusSet_Deploy()
{
	if [ -d $CUSTOM_SETTING ]
	then
		echo "$SFDC_ORG customSettings detected"
		echo "build customSettings"
		ant migrateCustomSettings -Denv=$SFDC_ORG 2>&1 | tee $CUSETLOG
		antReturnCode=`grep "BUILD SUCCESSFUL" $CUSETLOG`
		case $antReturnCode in
		"BUILD SUCCESSFUL") HTML_REPORT_CustomSetting
				    echo $gitlatest > $LastSuccessbuild
				    ;;
		esac

		PublishLOG customsetting	

	fi
}

CusMetadata()
{
if [ -d changeSetDeploy/force-app/main/default/customMetadata ]
then

        if [ ! -d changeSetDeploy/force-app/main/default/objects ]
        then
        mkdir changeSetDeploy/force-app/main/default/objects
        fi
 
        for obj in $(find  changeSetDeploy/force-app/main/default/customMetadata/ -type f |sort -u| xargs -L1 -I% sh -c "basename %  | cut -d "." -f1")
        do
        cp src/objects/${obj} changeSetDeploy/force-app/main/default/objects/
        done

fi
}


#Retry failed build
RecRun()
{
	RETRY=$(grep retryFailedBuild ${serverProperty}| cut -d "=" -f2)
	INTERVAL=$(grep retryInterval ${serverProperty}| cut -d "=" -f2)

	case ${RETRY} in
	2) cd ${PARENTPATH}
	   echo "${bin}/deploySFDC.sh -o  ${PARENTARGET}" | at now + `echo ${INTERVAL}` minutes
	;;
	1) echo "${bin}/deploySFDC.sh -o ${SFDC_ORG}" | at now + `echo ${INTERVAL}` minutes
	;;
	*) 
	;;
	esac
}


CountDeployable()
{
	changesetFile=$(find changeSetDeploy -type f | egrep -v "package.xml|staticResourceFolders.txt" | wc -l)
	if [ ${changesetFile} -eq 0 ]
	then
	mail -s "---$SFDC_ORG---NO Deployment--Deployable Count [${changesetFile}] for commit($gitlast-$gitlatest) [`date +%d.%b.%Y` PST]" -r $FROM -c $CC  $TO  < /dev/null
	echo "NO Deployment--Deployable Count [${changesetFile}] for commits($gitlast-$gitlatest)" | tee $LOG
	Unlock
	fi
}


ChangeSetDeploy()
{

#Return from function if changeSetDeploy/force-app/main/default/ has no deployable
changesetFile=$(find changeSetDeploy/force-app/main/default/ -type f | egrep -v "package.xml|staticResourceFolders.txt" | wc -l)
  if [ ${changesetFile} -eq 0 ]
   then
   return 1
  fi

echo "Deploy $SFDC_ORG ... Press <Ctrl>+C to cancel within 20 sec"
sleep 20

# ---- capture START (IST) just before the deploy kicks off ----
START_TIME_IST="$(TZ=Asia/Kolkata date +'%m/%d/%Y %I:%M:%S %p IST')"
START_EPOCH="$(TZ=Asia/Kolkata date +%s)"

#Changeset deploy
sf project deploy start --concise --source-dir changeSetDeploy/force-app --target-org $SFDC_ORG 2>&1 | tee $LOG

# ---- capture END (IST) immediately after the deploy completes ----
END_TIME_IST="$(TZ=Asia/Kolkata date +'%m/%d/%Y %I:%M:%S %p IST')"
END_EPOCH="$(TZ=Asia/Kolkata date +%s)"

antReturnCode=`egrep -o "Status: Succeeded|ALREADY_IN_PROCESS|EXCEEDED_MAX_SIZE_REQUEST|UNKNOWN_EXCEPTION|Failed to send request" $LOG | sort -u`

case $antReturnCode in

	"Status: Succeeded") HTML_REPORT SUCCEEDED
	PublishLOG changeset
	echo $gitlatest > $LastSuccessbuild
	if [[ $GIT_FORCE -eq 1 ]]
	then
	echo $gitlatest > $LastSuccessbuildFull
	git log -n1 --format=format:"%H" src/commonLabel/CustomLabels.labels-meta.xml > build/LastCommonCL.txt
	fi
	echo 1 > ${TRIGGER}

	;;

	"ALREADY_IN_PROCESS") HTML_REPORT LOCKED
	PublishLOG changeset
        #Don't trigger Relay
        #retry
        RecRun
        #Unlock, Set RelayTrigger & Exit
        FAIL_EXIT
	;;

       "EXCEEDED_MAX_SIZE_REQUEST") HTML_REPORT EXCEEDED_MAX_SIZE_REQUEST
        PublishLOG changeset
        #Don't trigger Relay
        #retry
        RecRun
        #Unlock, Set RelayTrigger & Exit
        FAIL_EXIT
        ;;
	
	"Failed to send request") HTML_REPORT Failed_to_send_request
        PublishLOG changeset
        #Don't trigger Relay
        #retry
        RecRun
        #Unlock, Set RelayTrigger & Exit
        FAIL_EXIT
        ;;

        "UNKNOWN_EXCEPTION") HTML_REPORT UNKNOWN_EXCEPTION
        PublishLOG changeset
        #Don't trigger Relay
        #retry
        RecRun
        #Unlock, Set RelayTrigger & Exit
        FAIL_EXIT
        ;;
	*)
	echo "Converting Error Log to Json...!!"

	sf project deploy start --json --source-dir changeSetDeploy/force-app --target-org $SFDC_ORG > $LOG.filtered 2>/dev/null
	#sed -e '/componentFailures/,$!d' $LOG.pre.filtered > $LOG.filtered
	

	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")


	
	#restore IFS
	IFS=$SAVEIFS


    HTML_REPORT FAILED
	PublishLOG changeset

			
	#retry
	RecRun
	

	#Unlock, Set RelayTrigger & Exit
	FAIL_EXIT
	;;
esac
}

HTML_REPORT() {
  Report=$1

  : > "$HTMLLog"

  # ---- config / prerequisites ----
  UI_COLORS_JSONC=${property}/ui_colors.jsonc
  UI_COLORS_JSONC="${UI_COLORS_JSONC:-ui_colors.jsonc}"
  UI_COLORS_JSON_STRICT="/tmp/ui_colors.$$.$RANDOM.json"

  _esc(){ sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }
  _fatal(){
    echo "[FATAL] $1"
    printf "%s\n" "[FATAL] $1" | mutt -s "---${SFDC_ORG}--- UI Color Config Error" "${mutt_MAIL_LIST}" 2>/dev/null
    rm -f "$UI_COLORS_JSON_STRICT" 2>/dev/null
    exit 1
  }

  command -v jq >/dev/null 2>&1 || _fatal "jq not found (needed for UI colors)."
  [ -f "$UI_COLORS_JSONC" ] || _fatal "UI colors JSONC not found at: $UI_COLORS_JSONC"

  # strip JSONC comments -> strict JSON
  sed -E ':a; s@/\*[^*]*\*+([^/*][^*]*\*+)*/@@g; ta' "$UI_COLORS_JSONC" \
  | sed -E 's@\r$@@' \
  | sed -E 's@//[[:space:]]*.*$@@' \
  | sed '/^[[:space:]]*$/d' > "$UI_COLORS_JSON_STRICT" \
  || _fatal "Failed producing strict JSON from $UI_COLORS_JSONC"

  [ -s "$UI_COLORS_JSON_STRICT" ] || _fatal "Empty strict JSON after stripping ($UI_COLORS_JSONC)."
  jq empty "$UI_COLORS_JSON_STRICT" >/dev/null 2>&1 || _fatal "ui_colors.jsonc invalid after stripping comments."

  HEX_RE='^#[0-9A-Fa-f]{6}$'
  _getc(){ jq -r "$1 // empty" "$UI_COLORS_JSON_STRICT"; }
  _ishex(){ [[ "$1" =~ $HEX_RE ]]; }

  required_keys=(
    '.header.success_bg' '.header.failure_bg' '.header.text'
    '.plate.page_bg' '.plate.background' '.plate.border'
    '.run_details.strip_success_bg' '.run_details.strip_failure_bg' '.run_details.title_text'
    '.chips.success_bg' '.chips.failure_bg' '.chips.success_text' '.chips.failure_text' '.chips.border'
    '.quick_links.tile_1_bg' '.quick_links.tile_2_bg' '.quick_links.tile_3_bg' '.quick_links.tile_4_bg' '.quick_links.text' '.quick_links.gap_px'
    '.status_summary.deployment_success_bg' '.status_summary.deployment_failure_bg'
    '.status_summary.pmd_bg' '.status_summary.time_bg'
    '.status_summary.title_text' '.status_summary.label_text' '.status_summary.value_text' '.status_summary.corner_radius'
    '.pmd_review.header_bg' '.pmd_review.header_text' '.pmd_review.row_border'
    '.pmd_review.link_normal' '.pmd_review.link_high' '.pmd_review.text_high' '.pmd_review.text_normal'
    '.success_section.file_row_bg' '.success_section.file_row_border' '.success_section.author_row_bg' '.success_section.author_row_border' '.success_section.title_text'
    '.failure_section.error_row_bg' '.failure_section.error_row_border' '.failure_section.author_row_bg' '.failure_section.author_row_border' '.failure_section.title_text'
    '.footer.bg' '.footer.text'
  )
  bad=0
  for k in "${required_keys[@]}"; do
    v=$(_getc "$k")
    if [ -z "$v" ]; then
      if [[ "$k" == .success_section* ]]; then
        case "$k" in
          *.file_row_bg)       v=$(_getc '.changeset.file_row_bg');;
          *.file_row_border)   v=$(_getc '.changeset.file_row_border');;
          *.author_row_bg)     v=$(_getc '.changeset.author_row_bg');;
          *.author_row_border) v=$(_getc '.changeset.author_row_border');;
          *.title_text)        v=$(_getc '.changeset.title_text');;
        esac
      elif [[ "$k" == .failure_section* ]]; then
        case "$k" in
          *.error_row_bg)      v=$(_getc '.failures.error_row_bg');;
          *.error_row_border)  v=$(_getc '.failures.error_row_border');;
          *.author_row_bg)     v=$(_getc '.failures.author_row_bg');;
          *.author_row_border) v=$(_getc '.failures.author_row_border');;
          *.title_text)        v=$(_getc '.failures.title_text');;
        esac
      fi
    fi
    if [[ "$k" =~ gap_px|corner_radius ]]; then
      [ -n "$v" ] || { echo "[FATAL] Missing value for $k"; bad=1; }
    else
      _ishex "$v" || { echo "[FATAL] Missing/invalid color for key $k"; bad=1; }
    fi
  done
  [ $bad -eq 0 ] || _fatal "ui_colors.jsonc failed validation."

  # ---- read colors ----
  _hdr_s=$(_getc '.header.success_bg'); _hdr_f=$(_getc '.header.failure_bg'); _hdr_txt=$(_getc '.header.text')
  _page_bg=$(_getc '.plate.page_bg'); _plate_bg=$(_getc '.plate.background'); _plate_border=$(_getc '.plate.border')
  _run_s=$(_getc '.run_details.strip_success_bg'); _run_f=$(_getc '.run_details.strip_failure_bg'); _run_title=$(_getc '.run_details.title_text')
  _chip_bg_s=$(_getc '.chips.success_bg'); _chip_bg_f=$(_getc '.chips.failure_bg'); _chip_txt_s=$(_getc '.chips.success_text'); _chip_txt_f=$(_getc '.chips.failure_text'); _chip_border=$(_getc '.chips.border')
  _ql1=$(_getc '.quick_links.tile_1_bg'); _ql2=$(_getc '.quick_links.tile_2_bg'); _ql3=$(_getc '.quick_links.tile_3_bg'); _ql4=$(_getc '.quick_links.tile_4_bg'); _ql_text=$(_getc '.quick_links.text'); _ql_gap=$(_getc '.quick_links.gap_px')
  _status_s=$(_getc '.status_summary.deployment_success_bg'); _status_f=$(_getc '.status_summary.deployment_failure_bg'); _status_pmd=$(_getc '.status_summary.pmd_bg'); _status_time=$(_getc '.status_summary.time_bg')
  _status_title=$(_getc '.status_summary.title_text'); _status_label=$(_getc '.status_summary.label_text'); _status_value=$(_getc '.status_summary.value_text'); _status_radius=$(_getc '.status_summary.corner_radius')
  _pmd_hdr_bg=$(_getc '.pmd_review.header_bg'); _pmd_hdr_text=$(_getc '.pmd_review.header_text'); _pmd_row_border=$(_getc '.pmd_review.row_border'); _pmd_link_normal=$(_getc '.pmd_review.link_normal'); _pmd_link_high=$(_getc '.pmd_review.link_high'); _pmd_text_high=$(_getc '.pmd_review.text_high'); _pmd_text_normal=$(_getc '.pmd_review.text_normal')
  _succ_file_bg=$(_getc '.success_section.file_row_bg'); _succ_file_border=$(_getc '.success_section.file_row_border'); _succ_auth_bg=$(_getc '.success_section.author_row_bg'); _succ_auth_border=$(_getc '.success_section.author_row_border'); _succ_title=$(_getc '.success_section.title_text')
  _fail_err_bg=$(_getc '.failure_section.error_row_bg'); _fail_err_border=$(_getc '.failure_section.error_row_border'); _fail_auth_bg=$(_getc '.failure_section.author_row_bg'); _fail_auth_border=$(_getc '.failure_section.author_row_border'); _fail_title=$(_getc '.failure_section.title_text')
  _foot_bg=$(_getc '.footer.bg'); _foot_text=$(_getc '.footer.text')

  # ---- runtime values ----
  _RUN_IST="$(TZ=Asia/Kolkata date +'%d.%b.%Y %H:%M IST')"
  _API="${SetAPI:-N/A}"
  _BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo N/A)"
  _REPO="$(git config --get remote.origin.url 2>/dev/null || echo N/A)"

  _REQID=""
  if [ -f "$LOG" ]; then
    _REQID="$(grep -m1 -E 'Deploy ID[[:space:]]*:' "$LOG" | xargs | cut -d: -f2- | cut '-d ' -f2-)"
  fi
  _DEPUSER=""
  if [ -f "$LOG" ]; then
    _DEPUSER="$(grep -m1 -E 'Target Org[[:space:]]*:' "$LOG" | xargs | cut -d: -f2- | cut '-d ' -f2-)"
  fi

  if [ -f "$LOG.filtered" ]; then
    COMP_PASS="$(jq -r 'try (.result.details.componentSuccesses|length) catch 0' "$LOG.filtered" 2>/dev/null)"
    COMP_FAIL="$(jq -r 'try (.result.details.componentFailures|length) catch 0' "$LOG.filtered" 2>/dev/null)"
  else
    COMP_PASS="$(find changeSetDeploy/force-app/main/default -type f | egrep -v 'customSettings|staticResourceFolders.txt' | wc -l | xargs)"
    COMP_FAIL=0
  fi

  PAT_FILE="build/property/pmd_high_patterns.txt"
  pattern="$(grep -Ehv '^\s*($|#)' "$PAT_FILE" | tr -d '\r' | paste -sd'|' -)"
  [ -n "$pattern" ] || _fatal "PMD patterns file is empty: $PAT_FILE"

  CLASS_COUNT=$(ls changeSetDeploy/force-app/main/default/classes/*.cls 2>/dev/null | wc -l | xargs)
  TRIGGER_COUNT=$(ls changeSetDeploy/force-app/main/default/triggers/*.trigger 2>/dev/null | wc -l | xargs)

  _sum_grep_matches() {
    local dir="$1"
    local total=0 n
    if [ -d "$dir" ]; then
      n=$(find "$dir" -maxdepth 1 -type f -name '*.txt' -print0 2>/dev/null \
          | xargs -0 -r grep -Eh "$pattern" 2>/dev/null | wc -l | xargs)
      total=$(( total + ${n:-0} ))
    fi
    echo "$total"
  }
  PMD_HIGH_CLS=$(_sum_grep_matches "PMDReport/currentpmdoutput/changeSetDeploy/force-app/main/default/classes")
  PMD_HIGH_TRG=$(_sum_grep_matches "PMDReport/currentpmdoutput/changeSetDeploy/force-app/main/default/triggers")
  PMD_HIGH_TOTAL=$(( PMD_HIGH_CLS + PMD_HIGH_TRG ))

  if [ "$CLASS_COUNT" -eq 0 ] && [ "$TRIGGER_COUNT" -eq 0 ]; then
    PMD_HIGH_CLS=0
    PMD_HIGH_TRG=0
    PMD_HIGH_TOTAL=0
  fi

  if [ -z "$START_TIME_IST" ] && [ -f "$deployLogFile" ]; then
    START_TIME_IST="$(tac "$deployLogFile" | grep -m1 'Build Start Time - ' | sed 's/.* - //')"
  fi
  if [ -z "$END_TIME_IST" ] && [ -f "$deployLogFile" ]; then
    END_TIME_IST="$(tac "$deployLogFile" | grep -m1 'Build End Time - ' | sed 's/.* - //')"
  fi

  _time_only(){
    local ts="$1"
    [ -n "$ts" ] || { echo ""; return; }
    TZ=Asia/Kolkata date -d "$ts" +'%I:%M %p IST' 2>/dev/null || echo "$ts"
  }
  START_TIME_IST_ONLY="$(_time_only "$START_TIME_IST")"
  END_TIME_IST_ONLY="$(_time_only "$END_TIME_IST")"

  if [ -n "$START_TIME_IST" ] && [ -n "$END_TIME_IST" ]; then
    _start_sec=$(TZ=Asia/Kolkata date -d "$START_TIME_IST" +%s 2>/dev/null || echo "")
    _end_sec=$(TZ=Asia/Kolkata date -d "$END_TIME_IST" +%s 2>/dev/null || echo "")
    if [ -n "$_start_sec" ] && [ -n "$_end_sec" ]; then
      _dur=$(( _end_sec - _start_sec ))
      _h=$((_dur/3600)); _m=$(((_dur%3600)/60)); _s=$((_dur%60))
      TOTAL_DURATION=$(printf "%02dh:%02dm:%02ds" "$_h" "$_m" "$_s")
    else
      TOTAL_DURATION="${TOTAL_DURATION:-N/A}"
    fi
  else
    TOTAL_DURATION="${TOTAL_DURATION:-N/A}"
  fi

  if [ "$Report" != "SUCCEEDED" ] && [ -f "$LOG.filtered" ] && { [ -z "$START_TIME_IST" ] || [ -z "$END_TIME_IST" ]; }; then
    JSON_CREATED="$(jq -r '.result.createdDate // empty' "$LOG.filtered" 2>/dev/null)"
    JSON_COMPLETED="$(jq -r '.result.completedDate // empty' "$LOG.filtered" 2>/dev/null)"
    if [ -n "$JSON_CREATED" ]; then
        START_TIME_IST="$(TZ=Asia/Kolkata date -d "$JSON_CREATED" +'%m/%d/%Y %I:%M:%S %p IST')"
    fi
    if [ -n "$JSON_COMPLETED" ]; then
        END_TIME_IST="$(TZ=Asia/Kolkata date -d "$JSON_COMPLETED"  +'%m/%d/%Y %I:%M:%S %p IST')"
    fi
    START_TIME_IST_ONLY="$(_time_only "$START_TIME_IST")"
    END_TIME_IST_ONLY="$(_time_only "$END_TIME_IST")"
    _start_sec=$(TZ=Asia/Kolkata date -d "$START_TIME_IST" +%s 2>/dev/null || echo "")
    _end_sec=$(TZ=Asia/Kolkata date -d "$END_TIME_IST" +%s 2>/dev/null || echo "")
    if [ -n "$_start_sec" ] && [ -n "$_end_sec" ]; then
        _dur=$(( _end_sec - _start_sec ))
        _h=$((_dur/3600)); _m=$(((_dur%3600)/60)); _s=$((_dur%60))
        TOTAL_DURATION=$(printf "%02dh:%02dm:%02ds" "$_h" "$_m" "$_s")
    fi
  fi

  OPEN_LOGS_URL="https://cdnsfdc.cadence.com/SFDC_GIT_LOG/${SFDC_ORG}.GIT_${gitlast}-${gitlatest}.${DATE}"
  ORIG_PMD_URL="https://cdnsfdc.cadence.com/PMDOUTPUT/${SFDC_ORG}"
  FORCE_DEPLOY_URL="https://cdnsfdc.cadence.com/SFDC_GIT_LOG/${SFDC_ORG}.GIT_${gitlast}-${gitlatest}.${DATE}/$(basename "${HTMLFDLog:-$HTMLLog}").${DATE}"

  if [ "$Report" = "SUCCEEDED" ]; then
    _hdr_bg="$_hdr_s"; _status_bg="$_status_s"; _chip_bg="$_chip_bg_s"; _chip_txt="$_chip_txt_s"
  else
    _hdr_bg="$_hdr_f"; _status_bg="$_status_f"; _chip_bg="$_chip_bg_f"; _chip_txt="$_chip_txt_f"
  fi

  resolve_src_from_json_name() {
    local jname="$1" stem f_cs f_src
    stem="$(basename "${jname}")"; stem="${stem%.*}"
    f_cs="$(find changeSetDeploy/force-app/main/default -type f -name "${stem}.*" -o -type d -name "${stem}" 2>/dev/null | head -n1)"
    if [ -n "$f_cs" ] && [ -d "$f_cs" ]; then
      f_cs="$(find "$f_cs" -type f -name "${stem}.*" 2>/dev/null | head -n1)"
    fi
    if [ -z "$f_cs" ] && [ -f "$SFCliBuildList" ]; then
      f_cs="$(grep -F "/${stem}." "$SFCliBuildList" | head -n1)"
    fi
    if [ -z "$f_cs" ]; then
      f_cs="$(find src -type f -name "${stem}.*" 2>/dev/null | head -n1)"
    fi
    [ -z "$f_cs" ] && return 1
    if [[ "$f_cs" == changeSetDeploy/force-app/main/default/* ]]; then
      f_src="${f_cs/changeSetDeploy\/force-app\/main\/default/src}"
    else
      f_src="$f_cs"
    fi
    case "$f_src" in
      src/labels/CustomLabels.labels-meta.xml)
        f_src="src/env/${SFDC_ORG}/customLabel/CustomLabels.labels-meta.xml";;
      src/customMetadata/*|src/remoteSiteSettings/*)
        f_src="${f_src/src/src\/env\/${SFDC_ORG}}";;
    esac
    printf '%s\n' "$f_src"
  }

  # Font scale (smaller as requested)
  _FONT_BASE="font:10px Arial,Helvetica,sans-serif;"
  _FONT_BASE_BOLD="font:bold 10px Arial,Helvetica,sans-serif;"
  _FONT_SECTION_HDR="font:bold 11px Arial,Helvetica,sans-serif;"
  _FONT_MAIN_HDR="font:bold 14px Arial,Helvetica,sans-serif;"   # keep main header readable
  _FONT_RUN_HDR="font:bold 11px Arial,Helvetica,sans-serif;"

  # Visible placeholder logo (32x32 teal square) if REPORT_LOGO not supplied
  _logo_src="${REPORT_LOGO:-data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABbklEQVRYR+2WvUrDUBSGv7mQhCIWIhrCwiCKGxsLW1tZWrcQBBFFxMIgY2thYW1trE3/AW0trY2NgYCFhY2Ah2ZLcvIGc6SZnMu7MnDkzs5ISkHcGiKKb8GfAYkAZcADuAl6A+cAF8A+8BvzMFQJgGjAJF7JrkFPhCnVwBZwBngAVgJ3gDdaAF0AC2B24Bn4B0oAPQrt/EtgLP8bW3vcAR0DLeAIWAFW4AA8AD8BPwBR4KfLz0UJTgMerre8N3n2mS8RmqbJ5fLwOu6Lqte13Xdf1SmLIsg2maZv+puu6/X6/1qtFqtRqNRuPxOBwOguVyuaZpms/ncLlc1Wo1QqlU2mwWQqG43W6/X6XS6XQ6/X6z2Qy+Wy2Ww2pVJJOp0Ot9uNvN9vt9vtfLpeL4/H4gEqlwufzyWRyOBwOt9sN4PF4n8/nzczMTHq9Ho/HYTabzWKx2Gw2g29vb6/X6+Uy2bIsf0Wg0mh8OhzqdDq/Xa5Ik2mz2fz6f12g04HA4PB4PJBIJBK/Xi0Qi0W63S5IkHo+Hw+Fw2Gw2Wq0WmUzGx8cH+P1+AJKqqjzP+/0f6DBFYCJifcEAAAAASUVORK5CYII=}"

  _CARD_WIDTH=880

  cat >>"$HTMLLog" <<HTML_TOP
<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style type="text/css">
  a.cta { text-decoration:none !important; color:${_ql_text} !important; }
  a.cta:hover { text-decoration:underline !important; }
  .wrap { word-wrap:break-word; word-break:break-word; }
</style>
</head>
<body style="margin:0;padding:0;background:${_page_bg};">
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:${_page_bg};"><tr><td align="center">
HTML_TOP

  # Header with logo
  cat >>"$HTMLLog" <<EOF
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="${_CARD_WIDTH}" style="max-width:${_CARD_WIDTH}px;margin:6px auto;">
    <tr>
      <td style="background:${_hdr_bg};padding:6px 10px;color:${_hdr_txt};${_FONT_MAIN_HDR}line-height:16px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
          <tr>
            <td style="padding:0 10px 0 0;vertical-align:middle;">
              <img src="${_logo_src}" alt="Logo" style="height:32px;width:32px;display:block;">
            </td>
            <td style="padding:0;${_FONT_MAIN_HDR}color:${_hdr_txt};vertical-align:middle;white-space:nowrap;">
              ${SFDC_ORG} Deployment $([ "$Report" = "SUCCEEDED" ] && echo "Success" || echo "Failure") Report
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
EOF

  # Card open
  cat >>"$HTMLLog" <<EOF
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="${_CARD_WIDTH}" style="max-width:${_CARD_WIDTH}px;background:${_plate_bg};border:1px solid ${_plate_border};">
    <tr><td style="padding:10px 12px;">
EOF

  # Run Details box (full width)
  cat >>"$HTMLLog" <<EOF
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border:1px solid ${_chip_border};border-radius:4px;margin:0 0 8px 0;">
    <tr>
      <td style="padding:6px 8px;text-align:center;${_FONT_RUN_HDR}color:${_run_title};border-bottom:1px solid ${_chip_border};">
        Run Details
      </td>
    </tr>
    <tr>
      <td style="padding:6px 8px 8px 8px;">
        <!-- Row 1 -->
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 auto 4px auto;">
          <tr>
EOF

  # Chip helper (smaller fonts, consistent height)
  _emit_chip_cell(){
    local label="$1" value="$2"
    cat <<CHIP >>"$HTMLLog"
            <td style="padding:2px 6px 2px 0;vertical-align:top;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="background:${_chip_bg};border:1px solid ${_chip_border};border-radius:3px;">
                <tr>
                  <td style="padding:4px 6px;min-width:130px;max-width:170px;${_FONT_BASE}color:${_chip_txt};line-height:12px;white-space:nowrap;">
                    <div style="font:700 9px Arial,Helvetica,sans-serif;color:${_chip_txt};letter-spacing:.3px;text-transform:uppercase;white-space:nowrap;">${label}</div>
                    <div style="font:10px Arial,Helvetica,sans-serif;color:${_chip_txt};white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">${value}</div>
                  </td>
                </tr>
              </table>
            </td>
CHIP
  }

  # Row 1 chips (REPO, BRANCH)
  _emit_chip_cell "REPO" "$(_esc <<<"$_REPO")"
  _emit_chip_cell "BRANCH" "$(_esc <<<"$_BRANCH")"

  cat >>"$HTMLLog" <<'EOF'
          </tr>
        </table>
        <!-- Row 2 -->
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 auto;">
          <tr>
EOF

  _emit_chip_cell "RUN (IST)" "$(_esc <<<"$_RUN_IST")"
  _emit_chip_cell "ORG NAME" "$(_esc <<<"$SFDC_ORG")"
  _emit_chip_cell "API" "$(_esc <<<"$_API")"
  _emit_chip_cell "REQUEST ID" "$(_esc <<<"$_REQID")"
  _emit_chip_cell "DEPLOY USER" "$(_esc <<<"$_DEPUSER")"

  cat >>"$HTMLLog" <<'EOF'
          </tr>
        </table>
      </td>
    </tr>
  </table>
EOF

  # Compact Quick Links box (content-width)
  GAP=$(( ${_ql_gap:-6} ))
  cat >>"$HTMLLog" <<EOF
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 10px 0;">
    <tr><td>
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #000000;border-radius:4px;padding:4px;display:inline-block;">
        <tr>
          <td style="padding:0 ${GAP}px 0 0;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="background:${_ql1};border-radius:3px;">
              <tr><td style="padding:0 10px;height:22px;line-height:22px;${_FONT_BASE_BOLD}">
                <a class="cta" href="${OPEN_LOGS_URL}" style="display:inline-block;line-height:22px;${_FONT_BASE_BOLD}color:${_ql_text};">Open Logs</a>
              </td></tr>
            </table>
          </td>
          <td style="padding:0 ${GAP}px 0 0;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="background:${_ql2};border-radius:3px;">
              <tr><td style="padding:0 10px;height:22px;line-height:22px;${_FONT_BASE_BOLD}">
                <a class="cta" href="${ORIG_PMD_URL}" style="display:inline-block;line-height:22px;${_FONT_BASE_BOLD}color:${_ql_text};">Original PMD Report</a>
              </td></tr>
            </table>
          </td>
          <td style="padding:0;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="background:${_ql4};border-radius:3px;">
              <tr><td style="padding:0 10px;height:22px;line-height:22px;${_FONT_BASE_BOLD}">
                <a class="cta" href="${FORCE_DEPLOY_URL}" style="display:inline-block;line-height:22px;${_FONT_BASE_BOLD}color:${_ql_text};">ForceDeploy</a>
              </td></tr>
            </table>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
EOF

  # Status Summary (unchanged logic, smaller font)
  _status_counts_html() {
    if [ "$Report" = "SUCCEEDED" ]; then
      echo "Passed: ${COMP_PASS}"
    else
      echo "Passed: ${COMP_PASS} &nbsp; • &nbsp; Failed: ${COMP_FAIL}"
    fi
  }
  _pmd_summary_html() {
    if [ "$CLASS_COUNT" -eq 0 ] && [ "$TRIGGER_COUNT" -eq 0 ]; then
      local warn_color="#c62828"
      echo "<div style=\"${_FONT_BASE_BOLD}color:${warn_color};\">Classes: 0 &nbsp; • &nbsp; Triggers: 0</div>"
      echo "<div style=\"${_FONT_BASE_BOLD}color:${warn_color};\">PMD analysis skipped</div>"
    else
      echo "<div style=\"${_FONT_BASE_BOLD}color:${_status_value};\">Classes: ${CLASS_COUNT} &nbsp; • &nbsp; Triggers: ${TRIGGER_COUNT}</div>"
      echo "<div style=\"${_FONT_BASE}color:${_status_value};\">High (Classes): ${PMD_HIGH_CLS} &nbsp; • &nbsp; High (Triggers): ${PMD_HIGH_TRG}</div>"
    fi
  }

  cat >>"$HTMLLog" <<EOF
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr><td style="padding:4px 2px 2px 2px;${_FONT_SECTION_HDR}color:${_status_title};">Status Summary</td></tr>
  </table>
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr>
      <td width="33%" valign="top" style="padding:2px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" height="78" style="background:${_status_bg};border-radius:${_status_radius};">
          <tr><td style="padding:6px;" valign="top">
            <div style="${_FONT_BASE}color:${_status_label};">DEPLOYMENT</div>
            <div style="${_FONT_BASE_BOLD}color:${_status_value};">$([ "$Report" = "SUCCEEDED" ] && echo "Succeeded" || echo "Failed")</div>
            <div style="${_FONT_BASE}color:${_status_value};">$(_status_counts_html)</div>
          </td></tr>
        </table>
      </td>
      <td width="33%" valign="top" style="padding:2px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" height="78" style="background:${_status_pmd};border-radius:${_status_radius};">
          <tr><td style="padding:6px;" valign="top">
            <div style="${_FONT_BASE}color:${_status_label};">PMD — CHANGESET</div>
            $(_pmd_summary_html)
          </td></tr>
        </table>
      </td>
      <td width="33%" valign="top" style="padding:2px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" height="78" style="background:${_status_time};border-radius:${_status_radius};">
          <tr><td style="padding:6px;" valign="top">
            <div style="${_FONT_BASE}color:${_status_label};">DURATION</div>
            <div style="${_FONT_BASE_BOLD}color:${_status_value};">${TOTAL_DURATION}</div>
            <div style="${_FONT_BASE}color:${_status_value};">Start: ${START_TIME_IST_ONLY:-N/A}<br>End: ${END_TIME_IST_ONLY:-N/A}</div>
          </td></tr>
        </table>
      </td>
    </tr>
  </table>
EOF

  # PMD Review (logic unchanged)
  _delta_pill(){
    local d="$1" bg="#eeeeee" bd="#dddddd" col="${_pmd_text_normal}" txt="$d"
    [ "$d" -gt 0 ] && { bg="#ffe3e3"; bd="#f5bcbc"; col="#b71c1c"; txt="+$d"; }
    [ "$d" -lt 0 ] && { bg="#e4f4e7"; bd="#bde0c0"; col="#1b5e20"; }
    cat <<PILL
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="display:inline-block;border:1px solid $bd;background:$bg;">
  <tr><td style="font:bold 10px Arial;color:$col;padding:1px 5px;white-space:nowrap;">$txt</td></tr>
</table>
PILL
  }

  if ! { [ "$CLASS_COUNT" -eq 0 ] && [ "$TRIGGER_COUNT" -eq 0 ]; }; then
    echo "<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\"><tr><td style=\"padding:10px 2px 4px 2px;${_FONT_SECTION_HDR}color:${_status_title};\">PMD Review</td></tr></table>" >>"$HTMLLog"

    if [ "$CLASS_COUNT" -gt 0 ]; then
      echo "<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" style=\"border:1px solid ${_pmd_row_border};border-collapse:collapse;\">" >>"$HTMLLog"
      echo "<thead><tr style=\"background:${_pmd_hdr_bg};\"><th align=\"left\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">CLASS NAME</th><th align=\"right\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">ORIGINAL (HIGH)</th><th align=\"right\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">CURRENT (HIGH)</th><th align=\"right\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">Δ HIGH</th><th align=\"left\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">AUTHOR</th></tr></thead><tbody>" >>"$HTMLLog"
      row_num=0
      for classePath in $(ls changeSetDeploy/force-app/main/default/classes/*.cls 2>/dev/null); do
        base="$(basename "$classePath" .cls)"
        currTxt="${base}.cls_currpmd.txt"
        orgTxt="${base}.cls_orgpmd.txt"
        pmd_html="/data/public/pmd_rule/$SFDC_ORG/${base}.cls_currpmd_orgpm.html"
        [ -f "$pmd_html" ] || pmd_html="/data/public/pmd_rule/$SFDC_ORG/${base}.cls_currpmd_orgpm.html"
        OriginalPmd=$(awk '/Original PMD Warnings/{f=1; next} f && /class="stat/{print; exit}' "$pmd_html" 2>/dev/null | sed -n 's/.*>\([0-9][0-9]*\)<.*/\1/p')
        CurrentPmd=$(awk  '/Current PMD Warnings/{f=1; next} f && /class="stat/{print; exit}' "$pmd_html" 2>/dev/null | sed -n 's/.*>\([0-9][0-9]*\)<.*/\1/p')
        OriginalPmd=${OriginalPmd:-0}; CurrentPmd=${CurrentPmd:-0}
        CurrseverityCnt=$(grep -Eh "$pattern" "PMDReport/currentpmdoutput/changeSetDeploy/force-app/main/default/classes/$currTxt" 2>/dev/null | wc -l | xargs)
        OrgseverityCnt=$(grep -Eh "$pattern" "PMDReport/orgpmdoutput/src/classes/$orgTxt" 2>/dev/null | wc -l | xargs)
        CurrseverityCnt=${CurrseverityCnt:-0}; OrgseverityCnt=${OrgseverityCnt:-0}
        delta=$(( CurrseverityCnt - OrgseverityCnt ))
        class_src="${classePath/changeSetDeploy\/force-app\/main\/default/src}"
        author_name="$(git log -1 --format='%an' "$class_src" 2>/dev/null | head -n1)"
        [ -n "$author_name" ] || author_name="N/A"
        link="https://cdnsfdc.cadence.com/pmd_rule/$SFDC_ORG/${base}.cls_currpmd_orgpm.html"
        display="${base}.cls"
        bg_color="#ffffff"; text_color="${_pmd_text_normal}"; link_color="${_pmd_link_normal}"
        [ $((row_num % 2)) -eq 1 ] && bg_color="#f7f7f7"
        row_left="#dcdcdc"
        if [ "$delta" -gt 0 ]; then
          bg_color="#ffefef"; text_color="${_pmd_text_high}"; link_color="${_pmd_link_high}"; row_left="#c62828"
        elif [ "$delta" -lt 0 ]; then
          bg_color="#ecf7ef"; row_left="#2e7d32"
        fi
        {
          echo "<tr style=\"background:${bg_color};border-bottom:1px solid ${_pmd_row_border};border-left:4px solid ${row_left};\">"
          echo "<td style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};word-wrap:break-word;\"><a href=\"$link\" style=\"text-decoration:underline;color:${link_color};\">$display</a></td>"
          echo "<td align=\"right\" style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};\">${OriginalPmd}-(${OrgseverityCnt})</td>"
          echo "<td align=\"right\" style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};\">${CurrentPmd}-(${CurrseverityCnt})</td>"
          echo "<td align=\"right\" style=\"padding:5px 6px;\">"
          _delta_pill "$delta"
          echo "</td>"
          echo "<td style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};\">$author_name</td>"
          echo "</tr>"
          echo "<tr><td colspan=\"5\" style=\"border-bottom:1px solid #dddddd;font-size:0;line-height:0;\">&nbsp;</td></tr>"
        } >>"$HTMLLog"
        row_num=$((row_num + 1))
      done
      echo "</tbody></table>" >>"$HTMLLog"
    fi

    if [ "$CLASS_COUNT" -gt 0 ] && [ "$TRIGGER_COUNT" -gt 0 ]; then
      echo "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"height:6px;line-height:6px;font-size:0;\">&nbsp;</td></tr></table>" >>"$HTMLLog"
    fi

    if [ "$TRIGGER_COUNT" -gt 0 ]; then
      echo "<table role=\"presentation\" cellpadding=\"0" cellspacing="0" border="0" width="100%" style="border:1px solid ${_pmd_row_border};border-collapse:collapse;\">" >>"$HTMLLog"
      echo "<thead><tr style=\"background:${_pmd_hdr_bg};\"><th align=\"left\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">TRIGGER NAME</th><th align=\"right\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">ORIGINAL (HIGH)</th><th align=\"right\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">CURRENT (HIGH)</th><th align=\"right\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">Δ HIGH</th><th align=\"left\" style=\"padding:6px 8px;${_FONT_BASE_BOLD}color:${_pmd_hdr_text};border-bottom:1px solid ${_pmd_row_border};\">AUTHOR</th></tr></thead><tbody>" >>"$HTMLLog"
      row_num=0
      for triggerPath in $(ls changeSetDeploy/force-app/main/default/triggers/*.trigger 2>/dev/null); do
        tbase="$(basename "$triggerPath" .trigger)"
        currTxt="${tbase}.trigger_currpmd.txt"
        orgTxt="${tbase}.trigger_orgpmd.txt"
        pmd_html="/data/public/pmd_rule/$SFDC_ORG/${tbase}.trigger_currpmd_orgpm.html"
        [ -f "$pmd_html" ] || pmd_html="/data/public/pmd_rule/$SFDC_ORG/${tbase}.trigger_currpmd_orgpm.html"
        OriginalPmd=$(awk '/Original PMD Warnings/{f=1; next} f && /class="stat/{print; exit}' "$pmd_html" 2>/dev/null | sed -n 's/.*>\([0-9][0-9]*\)<.*/\1/p')
        CurrentPmd=$(awk  '/Current PMD Warnings/{f=1; next} f && /class="stat/{print; exit}' "$pmd_html" 2>/dev/null | sed -n 's/.*>\([0-9][0-9]*\)<.*/\1/p')
        OriginalPmd=${OriginalPmd:-0}; CurrentPmd=${CurrentPmd:-0}
        CurrseverityCnt=$(grep -Eh "$pattern" "PMDReport/currentpmdoutput/changeSetDeploy/force-app/main/default/triggers/$currTxt" 2>/dev/null | wc -l | xargs)
        OrgseverityCnt=$(grep -Eh "$pattern" "PMDReport/orgpmdoutput/src/triggers/$orgTxt" 2>/dev/null | wc -l | xargs)
        CurrseverityCnt=${CurrseverityCnt:-0}; OrgseverityCnt=${OrgseverityCnt:-0}
        delta=$(( CurrseverityCnt - OrgseverityCnt ))
        trig_src="${triggerPath/changeSetDeploy\/force-app\/main\/default/src}"
        author_name="$(git log -1 --format='%an' "$trig_src" 2>/dev/null | head -n1)"
        [ -n "$author_name" ] || author_name="N/A"
        link="https://cdnsfdc.cadence.com/pmd_rule/$SFDC_ORG/${tbase}.trigger_currpmd_orgpm.html"
        display="${tbase}.trigger"
        bg_color="#ffffff"; text_color="${_pmd_text_normal}"; link_color="${_pmd_link_normal}"
        [ $((row_num % 2)) -eq 1 ] && bg_color="#f7f7f7"
        row_left="#dcdcdc"
        if [ "$delta" -gt 0 ]; then
          bg_color="#ffefef"; text_color="${_pmd_text_high}"; link_color="${_pmd_link_high}"; row_left="#c62828"
        elif [ "$delta" -lt 0 ]; then
          bg_color="#ecf7ef"; row_left="#2e7d32"
        fi
        {
          echo "<tr style=\"background:${bg_color};border-bottom:1px solid ${_pmd_row_border};border-left:4px solid ${row_left};\">"
          echo "<td style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};word-wrap:break-word;\"><a href=\"$link\" style=\"text-decoration:underline;color:${link_color};\">$display</a></td>"
          echo "<td align=\"right\" style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};\">${OriginalPmd}-(${OrgseverityCnt})</td>"
          echo "<td align=\"right\" style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};\">${CurrentPmd}-(${CurrseverityCnt})</td>"
          echo "<td align=\"right\" style=\"padding:5px 6px;\">"
          _delta_pill "$delta"
          echo "</td>"
          echo "<td style=\"padding:5px 8px;${_FONT_BASE}color:${text_color};\">$author_name</td>"
          echo "</tr>"
          echo "<tr><td colspan=\"5\" style=\"border-bottom:1px solid #dddddd;font-size:0;line-height:0;\">&nbsp;</td></tr>"
        } >>"$HTMLLog"
        row_num=$((row_num + 1))
      done
      echo "</tbody></table>" >>"$HTMLLog"
    fi
  fi

  # Success / Failure sections (font size adjustments consistent)
  SAVEIFS=$IFS; IFS=$(echo -en "\n\b")
  if [ "$Report" = "SUCCEEDED" ]; then
    find changeSetDeploy/force-app/main/default -type f \
      | egrep -v "customSettings|staticResourceFolders.txt" \
      | sed 's|^changeSetDeploy/force-app/main/default|src|' | sort -u > "${DEPLOYEDFILE}"
    changesetFile=$(find changeSetDeploy/force-app/main/default -type f | egrep -v "customSettings|staticResourceFolders.txt" | wc -l)
    echo "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin-top:8px;\"><tr><td style=\"${_FONT_SECTION_HDR}color:${_succ_title};padding:4px;\">Changeset file/s ...[${changesetFile}]</td></tr></table>" >>"$HTMLLog"
    NUM=1
    while read -r FILE; do
      [ "$FILE" = "src/labels/CustomLabels.labels-meta.xml" ] && FILE="src/env/${SFDC_ORG}/customLabel/CustomLabels.labels-meta.xml"
      if echo "$FILE" | grep -q "^customSettings"; then FILE=$(echo "$FILE" | sed -e 's/^customSettings\///'); fi
      [[ "$FILE" =~ "src/remoteSiteSettings/" ]] && FILE=$(echo "$FILE" | sed -e "s/^src/src\/env\/${SFDC_ORG}/")
      [[ "$FILE" =~ "src/customMetadata/"    ]] && FILE=$(echo "$FILE" | sed -e "s/^src/src\/env\/${SFDC_ORG}/")
      echo "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin-top:5px;\">
              <tr><td style=\"background:${_succ_file_bg};padding:5px 7px;border:1px solid ${_succ_file_border};\"><pre style=\"margin:0;white-space:pre-wrap;word-wrap:break-word;${_FONT_BASE}\">[$((NUM++))] ${FILE}</pre></td></tr>
              <tr><td style=\"background:${_succ_auth_bg};padding:5px 7px;border-left:1px solid ${_succ_auth_border};border-right:1px solid ${_succ_auth_border};border-bottom:1px solid ${_succ_auth_border};\"><pre style=\"margin:0;white-space:pre-wrap;word-wrap:break-word;${_FONT_BASE}\">Last author... $(git log -1 "$FILE" | sed -e 's/$/\ |/g' | xargs | sed -e 's/| |/|\ Comment:/g')</pre></td></tr>
            </table>" >>"$HTMLLog"
    done < "${DEPLOYEDFILE}"
  else
    echo "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin-top:8px;\"><tr><td style=\"${_FONT_SECTION_HDR}color:${_fail_title};padding:4px;\">All Component Failures:</td></tr></table>" >>"$HTMLLog"
    i=1
    if [ -f "$LOG.filtered" ]; then
      for failure in $(jq -c '.result.details.componentFailures[]' "$LOG.filtered"); do
        fileName=$(echo "$failure" | jq -r '.fileName')
        fileDisp=$(echo "$fileName" | sed 's|^changeSetDeploy/force-app/main/default/||')
        errorMsg=$(echo "$failure" | jq -r '.problem' | tr '\n' ' ' | tr '\r' ' ' | sed -e 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')
        echo "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin-top:5px;\"><tr><td style=\"background:${_fail_err_bg};padding:5px 7px;border:1px solid ${_fail_err_border};\"><pre style=\"margin:0;white-space:pre-wrap;word-wrap:break-word;${_FONT_BASE}\">$i. $fileDisp -- Error: $errorMsg</pre></td></tr>" >>"$HTMLLog"
        gitFile="$(resolve_src_from_json_name "$fileName")"
        if [ -n "$gitFile" ]; then
          LastAuthor=$(git log -1 "$gitFile" 2>/dev/null | sed -e 's/$/\ |/g' | xargs | sed -e 's/| |/|\ Comment:/g')
          echo "<tr><td style=\"background:${_succ_auth_bg};padding:5px 7px;border-left:1px solid ${_succ_auth_border};border-right:1px solid ${_succ_auth_border};border-bottom:1px solid ${_succ_auth_border};\"><pre style=\"margin:0;white-space:pre-wrap;word-wrap:break-word;${_FONT_BASE}\">GIT log >>> $gitFile
$LastAuthor</pre></td></tr></table>" >>"$HTMLLog"
        else
          echo "<tr><td style=\"background:${_succ_auth_bg};padding:5px 7px;border-left:1px solid ${_succ_auth_border};border-right:1px solid ${_succ_auth_border};border-bottom:1px solid ${_succ_auth_border};\"><pre style=\"margin:0;white-space:pre-wrap;word-wrap:break-word;${_FONT_BASE}\">No Git log available for $fileDisp</pre></td></tr></table>" >>"$HTMLLog"
        fi
        i=$((i+1))
      done
    fi
  fi
  IFS=$SAVEIFS

  # Footer
  cat >>"$HTMLLog" <<EOF
    </td></tr></table>
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="${_CARD_WIDTH}" style="max-width:${_CARD_WIDTH}px;margin:6px auto 10px;background:${_foot_bg};">
      <tr>
        <td align="center" style="padding:6px 8px;text-align:center;color:${_foot_text};${_FONT_BASE_BOLD}line-height:14px;">© 2025 Cadence Design Systems, Inc. | SFDC Deployment Report generated by the Cadence DevOps Team</td>
      </tr>
    </table>
</td></tr></table>
</body></html>
EOF

  EMAIL=${FROM} mutt -e 'set content_type=text/html' \
    -s "---${SFDC_ORG}--- SF-CLI ChangeSet Deploy ${Report} [`TZ=IST date +%d.%b.%Y` IST - git ${gitlast}-${gitlatest} ]" "${mutt_MAIL_LIST}" < "$HTMLLog"

  echo "DEBUG PMD: classCnt=${CLASS_COUNT} trigCnt=${TRIGGER_COUNT} highCls=${PMD_HIGH_CLS} highTrg=${PMD_HIGH_TRG} totalHigh=${PMD_HIGH_TOTAL}" >>"$LOG"

  rm -f "$UI_COLORS_JSON_STRICT" 2>/dev/null
}

HTML_REPORT_CustomSetting()
{

	CSLOG_PATH=changeSetDeploy/customSettings/logs
	
	echo "<HTML>" > $CUS_HTMLLog
	echo "<BODY>" >> $CUS_HTMLLog
	echo "<table width=100%>" >> $CUS_HTMLLog
   
	echo "<H3><tr><td bgcolor="LightBlue">${SFDC_ORG} CustomSetting Deployment</td></tr></H3>" >> $CUS_HTMLLog
	
	grep Object: $CUSETLOG | cut -d ":" -f2 | tr -d ' ' |sort|uniq > $CUSETLOG.filtered
	CS_Total=$(cat $CUSETLOG.filtered | wc -l)

	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")
    
	echo "<tr><td bgcolor="WHEAT">CustomSetting .....[${CS_Total}]</tr></td>" >> $CUS_HTMLLog

	NUM=1	
	for CS in $(cat $CUSETLOG.filtered)
	do
	echo "<tr><td bgcolor="LightBlue">[$((NUM++))] ${CS}</tr></td>" >> $CUS_HTMLLog
	
	#collect last line & add new line before "There", delete all line except the last one
	INSERT=$(tail -n 1 ${CSLOG_PATH}/${CS}.deploy.log | sed 's/There/\nThere/g' | sed '$!d')
	
	CS_FULL_LOG="<a href="https://cdnsfdc.cadence.com/SFDC_LOG/${SFDC_ORG}.SVN_${svnlast}-${svnlatest}.${DATE}/${SFDC_ORG}.changeSetDeploy.${DATE}/customSettings/logs/${CS}.deploy.log">Full Log</a>"
	
	
	if [ ! -z "$(echo ${INSERT} | grep -e "0 errors" )" ]
	then
	echo "<tr><td bgcolor="LightGreen">${INSERT} | "${CS_FULL_LOG}" | "${CS_viewvc}" </tr></td>" >> $CUS_HTMLLog
	else
	echo "<tr><td bgcolor="Yellow">${INSERT} | DEPLOYMENT FAILED | "${CS_FULL_LOG}" | "${CS_viewvc}" </tr></td>" >> $CUS_HTMLLog
	fi
	
	LastAuthor=`git log -1 src/env/${SFDC_ORG}/customSetting/${CS}.csv | sed -e 's/$/\ |/g'  | xargs | sed -e 's/| |/|\ Comment:/g'`
	echo "<tr><td bgcolor="Gainsboro"><PRE>" >> $CUS_HTMLLog            
	echo "Last author... ${LastAuthor}" >> $CUS_HTMLLog
	echo "</PRE></td></tr>" >> $CUS_HTMLLog
	
	done
	echo "</table>" >> $CUS_HTMLLog
	
	EMAIL=${FROM} mutt -e 'set content_type=text/html' \
	-s "---${SFDC_ORG}---CustomSetting Deploy Report [`date +%d.%b.%Y` PST - svn ${svnlast}-${svnlatest} ]" \
	"${mutt_MAIL_LIST}" < $CUS_HTMLLog

}

PublishLOG()
{

        LogPath="/data/public/SFDC_GIT_LOG/${SFDC_ORG}.GIT_${gitlast}-${gitlatest}.${DATE}"
        mkdir -p ${LogPath}
		
        if [ "$1" == "customsetting" ]
        then
              cp ${CUSETLOG} ${LogPath}/$SFDC_ORG.CusSetting.log.${DATE}
              cp -r changeSetDeploy/customSettings ${LogPath}/${SFDC_ORG}.changeSetDeploy.${DATE}/

        elif [ "$1" == "changeset" ]
        then
                cp ${CHANGESETLOG} ${LogPath}/$SFDC_ORG.Changeset.log.${DATE}
                cp ${LOG} ${LogPath}/$SFDC_ORG.Deploy.log.${DATE}
                cp ${HTMLLog} ${LogPath}/${SFDC_ORG}.Deploy.log.${DATE}.html
				
                if  [ -d changeSetDeploy/force-app/main/default/workflows ]
                then
                cp ${WFLOWLOG} ${LogPath}/$SFDC_ORG.Wflow.log.${DATE}
                fi

		cp ${CodeAnalyserFILE}    ${LogPath}/${SFDC_ORG}.CodeAnalysisReport.${DATE}.html
        cp -r changeSetDeploy ${LogPath}/${SFDC_ORG}.changeSetDeploy.${DATE}
        cp build/testClasses.txt  ${LogPath}/${SFDC_ORG}.testClasses.txt.${DATE}
        cp ${FD_FILE}   ${LogPath}/$(basename ${FD_FILE}).${DATE}
        cp ${ENV_FD_FILE}  ${LogPath}/$(basename ${ENV_FD_FILE}).${DATE}
        cp ${FD_COMBINED}  ${LogPath}/$(basename ${FD_COMBINED}).${DATE}
        cp ${FD_FILTERED}  ${LogPath}/$(basename ${FD_FILTERED}).${DATE}
        cp ${HTMLFDLog}    ${LogPath}/$(basename ${HTMLFDLog}).${DATE}

        fi
}


CheckAPIver()
{

local CheckAPI
local COMP
local API_minVer
local API
local ClaTrig=/tmp/${SFDC_ORG}_deploy_ClaTrig
rm ${ClaTrig}
local ExceptionList=build/property/${SFDC_ORG}.API_exceptionList.txt

APIVER()
{
# -h > suppress file name in grep
grep -h -Po "(?<=<apiVersion>).*(?=</apiVersion>)" $1 | cut -d "." -f1
}

check()
{
COMP=$1
API_minVer=$(grep APIMin ${serverProperty}| cut -d "=" -f2)


if [ -d changeSetDeploy/force-app/main/default/"${COMP}" ]
then
        for i in $(find changeSetDeploy/force-app/main/default/"${COMP}"/*.xml | grep -v -f "${ExceptionList}")
        do
                CheckAPI=$(APIVER $i)
                if [ "${CheckAPI}" -lt "${API_minVer}" ]
                then
                        CancelledReport
                        #retry
                        RecRun
                        CALL_SCRIPT FAILED
                        #Unlock, Set RelayTrigger & Exit
                        FAIL_EXIT
                fi
        done
fi
}

Collectcom()
{

COMP=$1
        for i in $(find changeSetDeploy/force-app/main/default/"${COMP}"/*.xml)
        do
                CheckAPI=$(APIVER $i)
                if [ "${CheckAPI}" -lt "${API_minVer}" ]
                then
                echo  $i | cut -d "/" -f 2-22 >> ${ClaTrig}
                fi
        done



}


AUTHOR()
{
git log -n 3 | grep "Author:" | awk '{print $2 " " $3}' | uniq 
}


Addinfo_AuthornAPI()
{

cp ${ClaTrig}  ${ClaTrig}.tmp
#remove meta.xml 
sed -e "s/-meta.xml//g"  ${ClaTrig} >> ${ClaTrig}.tmp
sort ${ClaTrig}.tmp | sed -e "s/$/,/g" > ${ClaTrig}


for i in $(cat ${ClaTrig} | cut -d "," -f1)
do

Author="$(AUTHOR $i)"
sed  -i  "s:${i},:${i}|${Author}:g" ${ClaTrig}

if [[ "${i}" =~ "meta.xml" ]]
then
API="$(APIVER $i)"
else
API=NA
fi
sed  -i  "s:${i}|:${i}|${API}|:g" ${ClaTrig}

done
#add column header
#sed -e "1ixml|API Version|Author" ${ClaTrig} >> ${ClaTrig}.tmp

cat ${ClaTrig}
}

CancelledReport()
{
Collectcom classes
Collectcom triggers
Addinfo_AuthornAPI

cat ${ClaTrig} | mail -s "---${SFDC_ORG}---Deployment Cancelled-git rev($gitlast-$gitlatest)-${COMP} below API ${API_minVer}" -r $FROM -c $CC  $TO
}

check classes
check triggers

}
Unlock()
{
	## process before exit #
	rm -f $LOCK
	exit
}
Chg_NonProd_Objs()

{
echo "Hardcode email replacement"
bash ${bin}/emails_mask_cli.sh ${SFDC_ORG}
#
#
echo "Hardcode URL Replacement"
bash ${bin}/change_object_in_nonprod_cli.sh ${SFDC_ORG}
#
echo "Modify Unified Registration email template"
bash ${bin}/modify_email_template_cli.sh ${SFDC_ORG}
##
echo "Modify Unified Registration email template"
bash ${bin}/modify_marketo_email_template_cli.sh ${SFDC_ORG}
}






# trap keyboard interrupt (control-c)
Trap()
{
	trap Unlock SIGINT
}

main "$@"
